require_relative 'dependency'
require_relative 'rm_static'
require_relative 'fix_frameworks'
require_relative 'fix_couchbase'


#source 'git@git.sbis.ru:mobileworkspace/specs.git'
#source 'git@git.sbis.ru:sbis/core-cocoapods-specs.git'

platform :ios, '10.0'

use_frameworks!

def app_pods
#dependency 'UISequence',            '../../ios-design'
#dependency 'SbisDesign',            '../../ios-design'
#dependency 'SbisUIComponents',    '../../ios-sbis-components'
dependency 'SbisTableKit',	'../'
dependency 'SbisDesign',	'../../../ios-design'
dependency 'SbisImageProvider',     '../../../ios-design'
dependency 'SbisUtils',             '../../../ios-utils'
dependency 'SbisServiceAPI',        '../../../ios-serviceAPI'
dependency 'SbisModel',                 '../../../ios-core'
dependency 'SbisFramework',  '../../../ios-utils'
dependency 'SbisLogger',           '../../../ios-utils'
end

target 'SbisTableKitDemo' do
	app_pods
end
